[2024-06-16T01:54:48.403+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T01:54:46.844163+00:00 [queued]>
[2024-06-16T01:54:48.411+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T01:54:46.844163+00:00 [queued]>
[2024-06-16T01:54:48.412+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-16T01:54:48.412+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-06-16T01:54:48.412+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-16T01:54:48.425+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fetch_and_save_data> on 2024-06-16 01:54:46.844163+00:00
[2024-06-16T01:54:48.433+0000] {standard_task_runner.py:55} INFO - Started process 1305 to run task
[2024-06-16T01:54:48.436+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_data_dag', 'fetch_and_save_data', 'manual__2024-06-16T01:54:46.844163+00:00', '--job-id', '32133', '--raw', '--subdir', 'DAGS_FOLDER/process_data.py', '--cfg-path', '/tmp/tmpqzmd36v7']
[2024-06-16T01:54:48.437+0000] {standard_task_runner.py:83} INFO - Job 32133: Subtask fetch_and_save_data
[2024-06-16T01:54:48.498+0000] {task_command.py:388} INFO - Running <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T01:54:46.844163+00:00 [running]> on host 74f2b0340b57
[2024-06-16T01:54:48.594+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_data_dag
AIRFLOW_CTX_TASK_ID=fetch_and_save_data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-16T01:54:46.844163+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-16T01:54:46.844163+00:00
[2024-06-16T01:54:48.596+0000] {logging_mixin.py:137} INFO - /opt/***
[2024-06-16T01:54:48.596+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_data.py", line 35, in fetch_and_save_data
    config = import_config()
  File "/opt/airflow/dags/process_data.py", line 18, in import_config
    with open('config/config.yaml', 'r') as config:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2024-06-16T01:54:48.605+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=process_data_dag, task_id=fetch_and_save_data, execution_date=20240616T015446, start_date=20240616T015448, end_date=20240616T015448
[2024-06-16T01:54:48.620+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32133 for task fetch_and_save_data ([Errno 2] No such file or directory: 'config/config.yaml'; 1305)
[2024-06-16T01:54:48.650+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-16T01:54:48.679+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
