[2024-06-16T02:23:53.309+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T02:23:51.939198+00:00 [queued]>
[2024-06-16T02:23:53.315+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T02:23:51.939198+00:00 [queued]>
[2024-06-16T02:23:53.315+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-16T02:23:53.315+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-06-16T02:23:53.315+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-16T02:23:53.324+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fetch_and_save_data> on 2024-06-16 02:23:51.939198+00:00
[2024-06-16T02:23:53.332+0000] {standard_task_runner.py:55} INFO - Started process 2797 to run task
[2024-06-16T02:23:53.334+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_data_dag', 'fetch_and_save_data', 'manual__2024-06-16T02:23:51.939198+00:00', '--job-id', '32321', '--raw', '--subdir', 'DAGS_FOLDER/process_data.py', '--cfg-path', '/tmp/tmp20340zk2']
[2024-06-16T02:23:53.334+0000] {standard_task_runner.py:83} INFO - Job 32321: Subtask fetch_and_save_data
[2024-06-16T02:23:53.375+0000] {task_command.py:388} INFO - Running <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T02:23:51.939198+00:00 [running]> on host d460cb06525f
[2024-06-16T02:23:53.423+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_data_dag
AIRFLOW_CTX_TASK_ID=fetch_and_save_data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-16T02:23:51.939198+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-16T02:23:51.939198+00:00
[2024-06-16T02:23:53.425+0000] {logging_mixin.py:137} INFO - /opt/***aqiode   dags|logs|webserver_config.py|plugins|***.cfg|***-worker.pid
[2024-06-16T02:23:53.426+0000] {logging_mixin.py:137} INFO - /opt/***aqiode   dags|logs|webserver_config.py|plugins|***.cfg|***-worker.pid
[2024-06-16T02:23:53.831+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_data.py", line 124, in fetch_and_save_data
    data = get_time_journey_to_city(origin, destination, config)
  File "/opt/airflow/dags/process_data.py", line 96, in get_time_journey_to_city
    waypoints_str = "|".join(waypoints)
TypeError: can only join an iterable
[2024-06-16T02:23:53.837+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=process_data_dag, task_id=fetch_and_save_data, execution_date=20240616T022351, start_date=20240616T022353, end_date=20240616T022353
[2024-06-16T02:23:53.846+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32321 for task fetch_and_save_data (can only join an iterable; 2797)
[2024-06-16T02:23:53.866+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-16T02:23:53.884+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
