[2024-06-15T00:50:02.292+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: example_passing_params_via_test_command.also_run_this scheduled__2024-06-15T00:49:00+00:00 [queued]>
[2024-06-15T00:50:02.299+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: example_passing_params_via_test_command.also_run_this scheduled__2024-06-15T00:49:00+00:00 [queued]>
[2024-06-15T00:50:02.299+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-15T00:50:02.300+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-06-15T00:50:02.300+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-15T00:50:02.313+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): also_run_this> on 2024-06-15 00:49:00+00:00
[2024-06-15T00:50:02.319+0000] {standard_task_runner.py:55} INFO - Started process 100740 to run task
[2024-06-15T00:50:02.322+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_passing_params_via_test_command', 'also_run_this', 'scheduled__2024-06-15T00:49:00+00:00', '--job-id', '28441', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_passing_params_via_test_command.py', '--cfg-path', '/tmp/tmpaxh3ciu7']
[2024-06-15T00:50:02.322+0000] {standard_task_runner.py:83} INFO - Job 28441: Subtask also_run_this
[2024-06-15T00:50:02.376+0000] {task_command.py:388} INFO - Running <TaskInstance: example_passing_params_via_test_command.also_run_this scheduled__2024-06-15T00:49:00+00:00 [running]> on host 27113cccce1f
[2024-06-15T00:50:02.411+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'also_run_this', field 'env'. Template: {'FOO': '{{ params.foo }}', 'MIFF': '{{ params.miff }}'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 663, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'foo'
[2024-06-15T00:50:02.412+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 663, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'foo'
[2024-06-15T00:50:02.420+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=example_passing_params_via_test_command, task_id=also_run_this, execution_date=20240615T004900, start_date=20240615T005002, end_date=20240615T005002
[2024-06-15T00:50:02.429+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28441 for task also_run_this ('dict object' has no attribute 'foo'; 100740)
[2024-06-15T00:50:02.453+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-15T00:50:02.467+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
