[2024-06-16T02:19:58.448+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T02:19:57.555567+00:00 [queued]>
[2024-06-16T02:19:58.454+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T02:19:57.555567+00:00 [queued]>
[2024-06-16T02:19:58.454+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-16T02:19:58.454+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-06-16T02:19:58.454+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-16T02:19:58.464+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fetch_and_save_data> on 2024-06-16 02:19:57.555567+00:00
[2024-06-16T02:19:58.472+0000] {standard_task_runner.py:55} INFO - Started process 2271 to run task
[2024-06-16T02:19:58.474+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_data_dag', 'fetch_and_save_data', 'manual__2024-06-16T02:19:57.555567+00:00', '--job-id', '32299', '--raw', '--subdir', 'DAGS_FOLDER/process_data.py', '--cfg-path', '/tmp/tmp5ypoqn1w']
[2024-06-16T02:19:58.474+0000] {standard_task_runner.py:83} INFO - Job 32299: Subtask fetch_and_save_data
[2024-06-16T02:19:58.516+0000] {task_command.py:388} INFO - Running <TaskInstance: process_data_dag.fetch_and_save_data manual__2024-06-16T02:19:57.555567+00:00 [running]> on host d460cb06525f
[2024-06-16T02:19:58.564+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_data_dag
AIRFLOW_CTX_TASK_ID=fetch_and_save_data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-16T02:19:57.555567+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-16T02:19:57.555567+00:00
[2024-06-16T02:19:58.566+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_data.py", line 35, in fetch_and_save_data
    config = import_config()
  File "/opt/airflow/dags/process_data.py", line 17, in import_config
    print(os.getcwd() + 'aqiode'+'   ' + os.listdir())
TypeError: can only concatenate str (not "list") to str
[2024-06-16T02:19:58.572+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=process_data_dag, task_id=fetch_and_save_data, execution_date=20240616T021957, start_date=20240616T021958, end_date=20240616T021958
[2024-06-16T02:19:58.579+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32299 for task fetch_and_save_data (can only concatenate str (not "list") to str; 2271)
[2024-06-16T02:19:58.605+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-16T02:19:58.624+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
